### ISSUE TITLE
error, Request failed. Try again later.

### ISSUE THREAD

**Issue by fernandooj** [opentok/servicekit-php#6]
hi Ankur
thanks for the library,
I have two questions
- Because I get this error
-I like to replace redis by sql
 
![servicekit](https://cloud.githubusercontent.com/assets/13096198/8404971/dfb7b1b4-1e16-11e5-9ee1-d8716d6c7611.png)

**Comment by aoberoi** [comment]
@fernandooj i think this is the same problem as we discussed in presencekit-php. it doesn't seem like you have set the URL Rewrite rules correctly. Please read the instructions in the README.

in order to replace redis with mysql, you need to change the implementation of the handlers in `web/index.php` which use redis to ones which use mysql instead. redis was chosen because it has a built-in concept of lists that can be used as a queue and have atomic operations. that could be challenging to implement in mysql, but it can be done.

**Comment by fernandooj** [comment]
this is my htacces:

RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^ index.php [QSA,L]


and servicekit-php-master/web/rep
I work well

**Comment by aoberoi** [comment]
Your URLs are not being mapped correctly. The project is set up to be hosted at the root level of your web server and not within a folder like `servicekit-php-master`. For example, you should be able to navigate to something like http://localhost/rep for the representative page, *not* something like http://.../web/rep.

**Comment by fernandooj** [comment]
thanks for the reply. I changed the url in the .htaccess not working for me.
RewriteRule ^ http: //localhost/servicekit-php-master/web/index.php [QSA, L]
- I need to install nginx.?
- I need to configure httpd.conf? how

greetings

**Comment by aoberoi** [comment]
@fernandooj which web server are you using locally to serve this?

**Comment by fernandooj** [comment]
xampp Fernando Ortiz JCEO / Director General Markapp 3162479980skype: fernandoortizjAv caracas 60-17 Oficina 200------------------------------------
 


     El Lunes, 6 de julio, 2015 19:20:25, Ankur Oberoi <notifications@github.com> escribió:
   

 @fernandooj which web server are you using locally to serve this?—

**Comment by aoberoi** [comment]
So this means you have Apache (which is the 'a' in xampp). You must follow the instructions for Apache in [the guide I previously mentioned](http://docs.slimframework.com/routing/rewrite/). Specifically, you need to create a VirtualHost entry so that you can server the application *from the root*. In the end, you should have a URL that just looks like "http://myhost.local" instead of "http://localhost/itdata/conferencia/servicekit-php-master/web". You might also find this guide useful, it that shows where the right configuration file (httpd.conf) is by default: http://sawmac.com/xampp/virtualhosts/.

**Comment by aoberoi** [comment]
closing for lack of feedback.
